name: Run Tests

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Create test environment variables
        run: |
          echo "# Test environment variables" > .env.test
          echo "NODE_ENV=test" >> .env.test
          echo "JWT_SECRET=test-jwt-secret" >> .env.test
          echo "ACCESS_TOKEN_SECRET=test-access-token-secret" >> .env.test
          echo "REFRESH_TOKEN_SECRET=test-refresh-token-secret" >> .env.test
      
      - name: Run tests
        run: npm test
      
      - name: Run linter
        run: npm run lint
